# Generated by Django 2.2 on 2019-07-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='paidBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Persons'),
        ),
    ]
