# Generated by Django 2.2 on 2019-07-04 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_auto_20190704_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='sheetId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.SheetData'),
        ),
    ]
