# Generated by Django 2.2 on 2019-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_auto_20190705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
