# Generated by Django 2.2 on 2019-07-06 18:02

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_auto_20190705_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='paidTo',
            field=django_mysql.models.ListCharField(models.CharField(blank=True, max_length=500, null=True), max_length=10, size=None),
        ),
    ]
