# Generated by Django 2.2 on 2019-07-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_auto_20190706_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputePayment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('owes', models.IntegerField(blank=True, null=True)),
                ('owed', models.IntegerField(blank=True, null=True)),
                ('owedTo', models.CharField(blank=True, max_length=500, null=True)),
                ('paidBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Persons')),
                ('sheetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.SheetData')),
            ],
        ),
    ]
