# Generated by Django 2.2 on 2019-07-08 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_computepayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computepayment',
            name='owedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.Expenses'),
        ),
    ]
