# Generated by Django 2.2 on 2019-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_auto_20190708_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persons',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='persons',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
