# Generated by Django 2.2 on 2019-08-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_auto_20190709_2326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComputePayment',
            new_name='Compute',
        ),
    ]
